[package]
name = "glados"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
axum = "0.5.16"
clap = { version = "4.0.17", features = ["derive"] }
discv5 = { git = "https://github.com/sigp/discv5.git", branch = "master" }
ethereum-types = "0.14.0"
jsonrpc = "0.13.0"
serde = "1.0.147"
serde_json = "1.0.86"
thiserror = "1.0.37"
tokio = { version = "1", features = ["full"] }
