[package]
name = "glados-monitor"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.64.0"
authors = ["Piper Merriam <piper@pipermerriam.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glados-core = { path = "../glados-core" }
entity = { path = "../entity" }
clap = "4.0.24"
web3 = "0.18.0"
