[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
enr = "0.7.0"
migration = { path = "../migration" }
sea-orm = { version = "0.10.1", features = ["sqlx-postgres", "sqlx-sqlite", "macros", "runtime-tokio-native-tls"] }
tokio = { version = "1.21.2", features = ["macros"] }
